export const FACTIONS={wei:{name:'위',identity:'속공·직접 피해·무기',color:'#315d92',power:'급습 명령'},shu:{name:'촉',identity:'도발·회복·반격',color:'#2e7d4f',power:'인덕의 수호'},wu:{name:'오',identity:'계략·화공·드로우',color:'#9b3030',power:'강동의 지략'},neutral:{name:'중립',identity:'범용 병력과 장비',color:'#6c6253'}};
export const RARITY={common:'보통',rare:'희귀',epic:'영웅',legendary:'전설'};
const troops={wei:['허창 창병','관도 궁기병','업성 철기병','합비 선봉대','하후가 친위대','오환 기병','청주병','호표기'],shu:['백이 의병','서촉 방패병','한중 산악병','형주 수비대','파서 창병','익주 철벽대','무당비군','백제성 수비병'],wu:['강동 수군','단양 정병','건업 화궁병','수춘 수병','여강 정찰대','장강 노병','파구 수채병','무창 강노병'],neutral:['황건 잔병','서량 기병','유주 궁수','형주 민병','하북 창병','산월 전사','남만 전사','교주 투창병']};
const names={wei:['조조','사마의','전위','하후돈','가후','장료','조인','허저','곽가','하후연'],shu:['유비','관우','장비','제갈량','조운','마초','황충','방통','위연','강유'],wu:['손권','주유','육손','손책','감녕','태사자','여몽','황개','노숙','대교'],neutral:['여포','동탁','초선','원소','공손찬','맹획','축융','화타','진궁','장각']};
const weapons=[['청룡언월도',5,4,2,'처치하면 다시 공격'],['장팔사모',4,3,3,'첫 공격 때 양옆에도 피해 1'],['의천검',4,3,2,'장착 시 카드 1장 드로우'],['청강검',3,2,3,'철갑을 무시'],['방천화극',7,6,2,'공격 후 다른 적에게 피해 3'],['고정도',3,2,2,'은신한 적도 공격 가능']];
const mounts=[['적토마',4,4,'돌진'],['적로',3,3,'철갑'],['절영',3,3,'은신'],['조황비전',2,2,'속공']];
const id=(f,n,i)=>`${f}-${i}-${n}`;
const unit=(f,n,c,a,h,r='common',keywords=[],text='')=>({id:id(f,n,c+a+h),faction:f,name:n,type:'unit',cost:c,attack:a,health:h,rarity:r,keywords,text});
const spell=(f,n,c,r,text,effect)=>({id:id(f,n,c),faction:f,name:n,type:'spell',cost:c,rarity:r,text,effect});
const equipment=(n,c,a,d,r='epic',text='')=>({id:id('neutral',n,c),faction:'neutral',name:n,type:'equipment',cost:c,attack:a,durability:d,rarity:r,text});
const mount=(n,c,heal,kw)=>({id:id('neutral',n,c),faction:'neutral',name:n,type:'mount',cost:c,rarity:'rare',text:`아군 장수 하나를 ${heal} 회복하고 ${kw} 부여`,heal,keyword:kw});
function generatedTroops(f){const out=[];for(let i=0;i<32;i++){const base=troops[f][i%troops[f].length];const c=1+i%7;let a=Math.max(1,Math.ceil(c*.72)+(f==='wei'?1:0));let h=Math.max(1,c+1+(f==='shu'?1:0)-(f==='wei'?1:0));const k=[];if(f==='wei'&&i%4===0)k.push(i%8===0?'돌진':'속공');if(f==='shu'&&i%3===0)k.push(i%6===0?'철갑':'도발');if(f==='wu'&&i%5===0)k.push('은신');if(f==='neutral'&&i%6===0)k.push('도발');out.push(unit(f,`${base} ${Math.floor(i/troops[f].length)+1}`,c,a,h,i>23?'rare':'common',k));}return out;}
function factionSpells(f){const defs={wei:[['선봉 돌격',1,'적 성에 피해 2','damageFortress'],['기습 명령',2,'아군 하나에게 공격력 +2와 속공','weiBuff'],['군량 약탈',2,'카드 2장 드로우. 내 성에 피해 1','draw2'],['전군 돌격',5,'모든 아군에게 공격력 +2','allAttack'],['낙석',3,'적 하나에게 피해 4','damage4'],['추격전',4,'이번 턴 아군 하나가 두 번 공격','windfury']],shu:[['의병 소집',1,'1/2 도발 의병 둘 소환','summonGuards'],['인덕의 수호',2,'아군 하나 생명력 +2. 없으면 성 2 회복','shuPower'],['백성 구휼',2,'내 성을 5 회복','heal5'],['철벽 진형',4,'모든 아군에게 철갑','allShield'],['도원결의',5,'아군 셋에게 +2/+2','tripleBuff'],['재정비',3,'죽은 아군 하나를 손으로 복귀','returnDead']],wu:[['화계',1,'적 하나에게 피해 2','damage2'],['연환계',2,'적 둘에게 피해 2','split2'],['강동의 지략',2,'계략 카드 하나 발견','discoverSpell'],['적벽 화공',5,'모든 적에게 피해 3','aoe3'],['수군 보급',3,'카드 2장 드로우','draw2'],['동남풍',4,'이번 턴 계략 피해 +2','spellPower']],neutral:[['응급 치료',2,'아군 하나를 4 회복','heal4'],['징병',2,'2/2 병사 둘 소환','summon2'],['매복',2,'비밀: 적이 성을 공격하면 3 피해','secretAmbush'],['군량 확보',1,'카드 1장 드로우','draw1'],['화살 세례',4,'모든 적에게 피해 2','aoe2'],['퇴각 명령',2,'아군 하나를 손으로 되돌림','bounceFriendly']]};return defs[f].map((d,i)=>spell(f,d[0],d[1],i>3?'epic':'rare',d[2],d[3]));}
function heroes(f){return names[f].map((n,i)=>{const legendary=i<6;const c=5+i%4;const kws=[];if(f==='wei'&&i%2===0)kws.push('속공');if(f==='shu'&&i%2===0)kws.push('도발');if(f==='wu'&&i%3===0)kws.push('은신');if(n==='여포')kws.push('돌진','질풍');if(n==='화타')kws.push('생명력 흡수');return unit(f,n,c,3+i%6,5+i%5,legendary?'legendary':'epic',kws,`${n}의 성향을 반영한 고유 장수`);});}
export const CARD_POOL=[...['wei','shu','wu','neutral'].flatMap(f=>[...generatedTroops(f),...factionSpells(f),...heroes(f)]),...weapons.map(w=>equipment(...w)),...mounts.map(m=>mount(...m))];
while(CARD_POOL.length<200){const i=CARD_POOL.length;CARD_POOL.push(unit('neutral',`전장 용병 ${i-159}`,1+i%7,1+i%6,2+i%7,i%9===0?'rare':'common',i%8===0?['도발']:[]));}
CARD_POOL.length=200;
export function legalCards(f){return CARD_POOL.filter(c=>c.faction==='neutral'||c.faction===f);}
export function draftOptions(f,rng=Math.random){const pool=legalCards(f),used=new Set(),out=[];while(out.length<3){const roll=rng()*100;const rarity=roll<68?'common':roll<91?'rare':roll<98?'epic':'legendary';let candidates=pool.filter(c=>c.rarity===rarity&&!used.has(c.id));if(!candidates.length)candidates=pool.filter(c=>!used.has(c.id));const card=candidates[Math.floor(rng()*candidates.length)];used.add(card.id);out.push(structuredClone(card));}return out;}
export function aiDeck(f,rng=Math.random){const pool=legalCards(f);const deck=[];const curve=[1,2,2,3,3,3,4,4,4,5,5,6,6,7,8,9,10];while(deck.length<30){const desired=curve[deck.length%curve.length];const candidates=pool.filter(c=>Math.abs(c.cost-desired)<=1);deck.push(structuredClone(candidates[Math.floor(rng()*candidates.length)]||pool[Math.floor(rng()*pool.length)]));}return deck;}
