import {aiDeck} from './cards.js';
const clone=v=>structuredClone(v),shuffle=(a,r=Math.random)=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const side=()=>({fortress:30,maxFortress:30,mana:0,maxMana:0,deck:[],hand:[],board:[],grave:[],fatigue:0,secret:null,powerUsed:false,spellPower:0});
export function createBattle(playerFaction,deck,enemyFaction,rng=Math.random){const first=rng()<.5?'player':'enemy';const state={playerFaction,enemyFaction,turn:first,round:0,winner:null,log:[],player:side(),enemy:side(),coin:first==='enemy'};state.player.deck=shuffle(deck,rng);state.enemy.deck=shuffle(aiDeck(enemyFaction,rng),rng);for(let i=0;i<(first==='player'?3:4);i++)draw(state,'player');for(let i=0;i<(first==='enemy'?3:4);i++)draw(state,'enemy');if(first==='enemy')state.player.hand.push({id:'coin',name:'동전',type:'spell',cost:0,rarity:'common',faction:'neutral',text:'이번 턴에만 마나 +1',effect:'coin'});else state.enemy.hand.push({id:'coin-ai',name:'동전',type:'spell',cost:0,rarity:'common',faction:'neutral',text:'이번 턴에만 마나 +1',effect:'coin'});startTurn(state,first);return state;}
export function draw(s,who){const p=s[who];if(p.hand.length>=10){if(p.deck.length)p.deck.shift();log(s,`${who==='player'?'내':'적'} 손패가 가득 차 카드가 소멸했습니다.`);return;}if(!p.deck.length){p.fatigue++;damageFortress(s,who,p.fatigue);log(s,`피로 피해 ${p.fatigue}`);return;}p.hand.push(p.deck.shift());}
export function startTurn(s,who){if(s.winner)return;s.turn=who;s.round++;const p=s[who];p.maxMana=Math.min(10,p.maxMana+1);p.mana=p.maxMana;p.powerUsed=false;p.spellPower=0;p.board.forEach(u=>{u.canAttack=true;u.attacksLeft=u.keywords?.includes('질풍')?2:1;u.frozen=false;});draw(s,who);log(s,`${who==='player'?'아군':'적군'} 턴 시작 · 마나 ${p.mana}`);}
export function endTurn(s,who){if(s.turn!==who||s.winner)return false;const next=who==='player'?'enemy':'player';startTurn(s,next);return true;}
export function playCard(s,who,handIndex,target=null){if(s.turn!==who||s.winner)return {ok:false,error:'내 턴이 아닙니다.'};const p=s[who],card=p.hand[handIndex];if(!card)return {ok:false,error:'카드가 없습니다.'};if(card.cost>p.mana)return {ok:false,error:'마나가 부족합니다.'};if(card.type==='unit'&&p.board.length>=7)return {ok:false,error:'전장이 가득 찼습니다.'};p.mana-=card.cost;p.hand.splice(handIndex,1);if(card.type==='unit'){const u={...clone(card),maxHealth:card.health,canAttack:card.keywords?.includes('돌진')||card.keywords?.includes('속공'),attacksLeft:1,shield:card.keywords?.includes('철갑'),stealth:card.keywords?.includes('은신'),equipment:null};p.board.push(u);return {ok:true,kind:'summon',unit:u};}
if(card.type==='equipment'){const u=resolveUnit(s,who,target);if(!u){p.mana+=card.cost;p.hand.splice(handIndex,0,card);return {ok:false,error:'장착할 아군을 선택하세요.'};}u.equipment={name:card.name,attack:card.attack,durability:card.durability,text:card.text};return {ok:true,kind:'equipment',unit:u};}
if(card.type==='mount'){const u=resolveUnit(s,who,target);if(!u){p.mana+=card.cost;p.hand.splice(handIndex,0,card);return {ok:false,error:'탈것을 줄 아군을 선택하세요.'};}u.health=Math.min(u.maxHealth,u.health+card.heal);u.keywords=[...new Set([...(u.keywords||[]),card.keyword])];if(card.keyword==='철갑')u.shield=true;if(['돌진','속공'].includes(card.keyword))u.canAttack=true;return {ok:true,kind:'mount',unit:u};}
applySpell(s,who,card,target);return {ok:true,kind:'spell'};}
function resolveUnit(s,who,target){if(target?.side&&Number.isInteger(target.index))return s[target.side].board[target.index];if(Number.isInteger(target))return s[who].board[target];return null;}
function applySpell(s,who,c,target){const me=s[who],enemy=s[who==='player'?'enemy':'player'],amount=(n)=>n+(me.spellPower||0);const enemyUnit=target?.side&&target.side!==who?resolveUnit(s,target.side,target):null;const friendly=target?.side===who?resolveUnit(s,who,target):null;switch(c.effect){case'coin':me.mana++;break;case'damageFortress':damageFortress(s,who==='player'?'enemy':'player',amount(2));break;case'damage2':enemyUnit?damageUnit(s,target.side,target.index,amount(2)):damageFortress(s,who==='player'?'enemy':'player',amount(2));break;case'damage4':enemyUnit?damageUnit(s,target.side,target.index,amount(4)):damageFortress(s,who==='player'?'enemy':'player',amount(4));break;case'heal5':me.fortress=Math.min(30,me.fortress+5);break;case'heal4':if(friendly)friendly.health=Math.min(friendly.maxHealth,friendly.health+4);break;case'draw1':draw(s,who);break;case'draw2':draw(s,who);draw(s,who);break;case'allAttack':me.board.forEach(u=>u.attack+=2);break;case'allShield':me.board.forEach(u=>u.shield=true);break;case'aoe2':enemy.board.slice().forEach((_,i)=>damageUnit(s,who==='player'?'enemy':'player',i,amount(2),true));cleanup(s);break;case'aoe3':enemy.board.slice().forEach((_,i)=>damageUnit(s,who==='player'?'enemy':'player',i,amount(3),true));cleanup(s);break;case'weiBuff':if(friendly){friendly.attack+=2;friendly.canAttack=true;friendly.keywords=[...new Set([...(friendly.keywords||[]),'속공'])];}break;case'shuPower':if(friendly){friendly.health+=2;friendly.maxHealth+=2;}else me.fortress=Math.min(30,me.fortress+2);break;case'spellPower':me.spellPower+=2;break;case'summonGuards':for(let i=0;i<2&&me.board.length<7;i++)me.board.push(token('의병',1,2,['도발']));break;case'summon2':for(let i=0;i<2&&me.board.length<7;i++)me.board.push(token('병사',2,2,[]));break;case'secretAmbush':me.secret='ambush';break;default:if(enemyUnit)damageUnit(s,target.side,target.index,amount(1));break;}cleanup(s);}
const token=(name,a,h,k)=>({id:`token-${name}-${Math.random()}`,name,type:'unit',cost:0,attack:a,health:h,maxHealth:h,keywords:k,canAttack:false,attacksLeft:1,shield:k.includes('철갑'),stealth:false});
export function heroPower(s,who,target=null){if(s.turn!==who)return {ok:false,error:'내 턴이 아닙니다.'};const p=s[who];if(p.powerUsed||p.mana<2)return {ok:false,error:'군령을 사용할 수 없습니다.'};p.mana-=2;p.powerUsed=true;if((who==='player'?s.playerFaction:s.enemyFaction)==='wei'){const u=resolveUnit(s,who,target);if(u){u.attack+=2;u.canAttack=true;}else damageFortress(s,who==='player'?'enemy':'player',1);}else if((who==='player'?s.playerFaction:s.enemyFaction)==='shu'){const u=resolveUnit(s,who,target);if(u){u.health+=2;u.maxHealth+=2;}else p.fortress=Math.min(30,p.fortress+2);}else{const enemy=who==='player'?'enemy':'player';const u=resolveUnit(s,enemy,target);if(u)damageUnit(s,enemy,target.index,1);else damageFortress(s,enemy,1);draw(s,who);}cleanup(s);return {ok:true};}
export function validTargets(s,who,attackerIndex){const enemy=who==='player'?'enemy':'player',taunts=s[enemy].board.map((u,i)=>({u,i})).filter(x=>x.u.keywords?.includes('도발')&&!x.u.stealth);if(taunts.length)return taunts.map(x=>({side:enemy,index:x.i,type:'unit'}));return [...s[enemy].board.map((u,i)=>({side:enemy,index:i,type:'unit'})).filter(t=>!s[enemy].board[t.index].stealth),{side:enemy,type:'fortress'}];}
export function attack(s,who,attackerIndex,target){if(s.turn!==who||s.winner)return {ok:false,error:'공격할 수 없습니다.'};const enemy=who==='player'?'enemy':'player',a=s[who].board[attackerIndex];if(!a||!a.canAttack||a.attacksLeft<=0)return {ok:false,error:'아직 공격할 수 없습니다.'};const allowed=validTargets(s,who,attackerIndex);if(!allowed.some(t=>t.side===target.side&&t.type===target.type&&t.index===target.index))return {ok:false,error:'도발 부대를 먼저 공격해야 합니다.'};a.stealth=false;if(target.type==='fortress'){if(s[enemy].secret==='ambush'){s[enemy].secret=null;damageUnit(s,who,attackerIndex,3);if(!s[who].board[attackerIndex])return {ok:true};}damageFortress(s,enemy,totalAttack(a));}else{const d=s[enemy].board[target.index];const av=totalAttack(a),dv=totalAttack(d);damageUnit(s,enemy,target.index,av);damageUnit(s,who,attackerIndex,dv);}a.attacksLeft--;if(a.attacksLeft<=0)a.canAttack=false;if(a.equipment){a.equipment.durability--;if(a.equipment.durability<=0)a.equipment=null;}cleanup(s);return {ok:true,damage:totalAttack(a)};}
const totalAttack=u=>u.attack+(u.equipment?.attack||0);
export function damageUnit(s,who,index,amount,defer=false){const u=s[who].board[index];if(!u)return;if(u.shield){u.shield=false;return;}u.health-=amount;if(!defer&&u.health<=0)kill(s,who,index);}
function kill(s,who,index){const [u]=s[who].board.splice(index,1);if(u)s[who].grave.push(u);}
function cleanup(s){for(const who of ['player','enemy'])for(let i=s[who].board.length-1;i>=0;i--)if(s[who].board[i].health<=0)kill(s,who,i);checkWinner(s);}
function damageFortress(s,who,amount){s[who].fortress-=amount;checkWinner(s);}
function checkWinner(s){if(s.enemy.fortress<=0)s.winner='player';if(s.player.fortress<=0)s.winner='enemy';}
function log(s,msg){s.log.unshift(msg);s.log=s.log.slice(0,12);}
export function aiTurn(s,rng=Math.random){if(s.turn!=='enemy'||s.winner)return[];const events=[];let safety=30;while(safety--){const p=s.enemy;let playable=p.hand.map((c,i)=>({c,i})).filter(x=>x.c.cost<=p.mana&&(x.c.type!=='unit'||p.board.length<7));if(!playable.length)break;playable.sort((a,b)=>b.c.cost-a.c.cost);const pick=playable[0],target=chooseTarget(s,'enemy',pick.c,rng);const r=playCard(s,'enemy',pick.i,target);if(!r.ok)break;events.push({type:'play',card:pick.c});}
for(let i=0;i<s.enemy.board.length;i++){const u=s.enemy.board[i];if(!u.canAttack)continue;const targets=validTargets(s,'enemy',i);const target=targets.find(t=>t.type==='unit')||targets[targets.length-1];if(target){attack(s,'enemy',i,target);events.push({type:'attack',name:u.name,target});if(s.winner)break;}}
if(!s.winner&&s.enemy.mana>=2&&!s.enemy.powerUsed){heroPower(s,'enemy');events.push({type:'power'});}if(!s.winner)endTurn(s,'enemy');return events;}
function chooseTarget(s,who,c,rng){const enemy=who==='player'?'enemy':'player';if(['equipment','mount'].includes(c.type)&&s[who].board.length)return {side:who,index:Math.floor(rng()*s[who].board.length)};if(c.type==='spell'&&s[enemy].board.length&&/적 하나|피해/.test(c.text))return {side:enemy,index:Math.floor(rng()*s[enemy].board.length)};if(c.type==='spell'&&s[who].board.length&&/아군 하나/.test(c.text))return {side:who,index:0};return {side:enemy,type:'fortress'};}
