import {FACTIONS,CARD_POOL,RARITY,draftOptions} from './cards.js';
import {createBattle,playCard,attack,endTurn,heroPower,aiTurn,validTargets} from './game.js';
const app=document.querySelector('#app');
let screen='title',faction=null,draft=[],options=[],battle=null,drag=null,message='';
const enemyFaction=()=>['wei','shu','wu'].filter(f=>f!==faction)[Math.floor(Math.random()*2)];
function render(){if(screen==='title')renderTitle();else if(screen==='draft')renderDraft();else renderBattle();}
function renderTitle(){app.innerHTML=`<main class="title-screen"><div class="title-crest">城</div><p class="eyebrow">THREE KINGDOMS CARD ARENA</p><h1>삼국지<br><span>성채 투기장</span></h1><p class="lead">세 장 중 하나를 골라 30장 덱을 완성하고 적 성을 무너뜨리십시오.</p><div class="factions">${['wei','shu','wu'].map(f=>`<button class="faction-card ${f}" data-f="${f}"><b>${FACTIONS[f].name}</b><strong>${f==='wei'?'⚔️':f==='shu'?'🛡️':'🔥'}</strong><span>${FACTIONS[f].identity}</span><small>군령 · ${FACTIONS[f].power}</small></button>`).join('')}</div><div class="catalog">초기 카드 세트 <b>${CARD_POOL.length}</b>종 · 싱글플레이 투기장</div></main>`;app.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>startDraft(b.dataset.f));}
function startDraft(f){faction=f;draft=[];screen='draft';nextDraft();}
function nextDraft(){options=draftOptions(faction);render();}
function pick(i){draft.push(options[i]);if(draft.length>=30){battle=createBattle(faction,draft,enemyFaction());screen='battle';message='투기장 개전';render();if(battle.turn==='enemy')setTimeout(runAi,700);}else nextDraft();}
function cardMarkup(c,opts={}){const disabled=opts.disabled?' disabled':'';return `<article class="card rarity-${c.rarity} faction-${c.faction}${disabled}" data-card-index="${opts.index??''}" draggable="${opts.draggable?'true':'false'}"><div class="mana">${c.cost}</div><div class="card-art">${c.type==='unit'?'👤':c.type==='spell'?'📜':c.type==='equipment'?'🗡️':'🐎'}</div><div class="card-name">${c.name}</div><div class="card-type">${c.type==='unit'?'부대':c.type==='spell'?'계략':c.type==='equipment'?'무기':'탈것'} · ${RARITY[c.rarity]}</div><div class="card-text">${(c.keywords||[]).map(k=>`<b>${k}</b>`).join(' ')} ${c.text||''}</div>${c.type==='unit'?`<div class="attack">${c.attack}</div><div class="health">${c.health}</div>`:''}</article>`;}
function renderDraft(){app.innerHTML=`<main class="draft-screen"><header><div><p class="eyebrow">${FACTIONS[faction].name}군 투기장 징집</p><h2>세 장 중 한 장을 선택하십시오</h2></div><div class="draft-count"><b>${draft.length}</b><span>/ 30</span></div></header><div class="draft-progress"><i style="width:${draft.length/30*100}%"></i></div><section class="draft-options">${options.map((c,i)=>`<button class="draft-pick" data-pick="${i}">${cardMarkup(c)}</button>`).join('')}</section><aside class="curve"><b>현재 덱 ${draft.length}장</b><div>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<span>${n}<em>${draft.filter(c=>Math.min(10,c.cost)===n).length}</em></span>`).join('')}</div></aside></main>`;app.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>pick(+b.dataset.pick));}
function fortress(who){const p=battle[who],name=who==='player'?`${FACTIONS[battle.playerFaction].name}군 성채`:`${FACTIONS[battle.enemyFaction].name}군 성채`;return `<div class="fortress ${who}" data-target-side="${who}" data-target-type="fortress"><div class="castle">${p.fortress<=10?'🔥':'🏯'}</div><div><b>${name}</b><span>내구도 ${Math.max(0,p.fortress)} / 30</span></div><div class="fortress-hp"><i style="width:${Math.max(0,p.fortress)/30*100}%"></i></div></div>`;}
function unitMarkup(u,side,i){const atk=u.attack+(u.equipment?.attack||0);return `<div class="unit ${u.canAttack&&side==='player'?'ready':''} ${u.keywords?.includes('도발')?'taunt':''} ${u.stealth?'stealth':''}" data-unit-side="${side}" data-unit-index="${i}" data-target-side="${side}" data-target-index="${i}" data-target-type="unit"><div class="unit-art">${u.shield?'🛡️':u.stealth?'🌫️':'⚔️'}</div><b>${u.name}</b><small>${(u.keywords||[]).join(' · ')}</small>${u.equipment?`<em>${u.equipment.name} ${u.equipment.durability}</em>`:''}<span class="unit-atk">${atk}</span><span class="unit-hp">${u.health}</span></div>`;}
function renderBattle(){const p=battle.player,e=battle.enemy;app.innerHTML=`<main class="battle-screen faction-bg-${faction}"><header class="battle-top"><div>적 손패 ${e.hand.length} · 덱 ${e.deck.length}</div><div class="turn-label">${battle.turn==='player'?'나의 턴':'적의 턴'} · ${battle.round}턴</div><button class="small" id="newGame">새 게임</button></header>${fortress('enemy')}<section class="board enemy-board">${e.board.map((u,i)=>unitMarkup(u,'enemy',i)).join('')||'<div class="empty-board">적 전장</div>'}</section><div class="battle-line"><span>⚔ 전선 ⚔</span></div><section class="board player-board">${p.board.map((u,i)=>unitMarkup(u,'player',i)).join('')||'<div class="empty-board">카드를 이곳으로 끌어 소환</div>'}</section>${fortress('player')}<section class="hand-wrap"><div class="hand">${p.hand.map((c,i)=>cardMarkup(c,{index:i,draggable:battle.turn==='player',disabled:c.cost>p.mana})).join('')}</div><aside class="command"><div class="mana-orbs"><b>${p.mana}</b><span>/ ${p.maxMana}</span></div><button id="power" ${p.powerUsed||p.mana<2||battle.turn!=='player'?'disabled':''}>군령 2<br><small>${FACTIONS[faction].power}</small></button><button id="endTurn" ${battle.turn!=='player'?'disabled':''}>턴 종료</button></aside></section><div class="combat-log">${battle.log.slice(0,5).map(x=>`<span>${x}</span>`).join('')}</div>${message?`<div class="toast">${message}</div>`:''}${battle.winner?`<div class="result"><h2>${battle.winner==='player'?'승리':'패배'}</h2><p>${battle.winner==='player'?'적 성채를 함락했습니다.':'아군 성채가 무너졌습니다.'}</p><button id="restart">다시 시작</button></div>`:''}</main>`;wireBattle();}
function wireBattle(){document.querySelector('#newGame').onclick=()=>{screen='title';battle=null;render();};document.querySelector('#restart')?.addEventListener('click',()=>{screen='title';battle=null;render();});document.querySelector('#endTurn')?.addEventListener('click',()=>{endTurn(battle,'player');message='적군 행동 중';render();setTimeout(runAi,650);});document.querySelector('#power')?.addEventListener('click',()=>{const r=heroPower(battle,'player');message=r.ok?'군령 발동':r.error;render();});document.querySelectorAll('.card[draggable="true"]').forEach(el=>{el.addEventListener('dragstart',ev=>{drag={kind:'card',index:+el.dataset.cardIndex};ev.dataTransfer.setData('text/plain','card');});el.addEventListener('click',()=>quickPlay(+el.dataset.cardIndex));});document.querySelectorAll('.unit[data-unit-side="player"]').forEach(el=>{el.draggable=true;el.addEventListener('dragstart',ev=>{drag={kind:'unit',index:+el.dataset.unitIndex};ev.dataTransfer.setData('text/plain','unit');});el.addEventListener('click',()=>selectAttacker(+el.dataset.unitIndex));});document.querySelectorAll('[data-target-side],.player-board').forEach(el=>{el.addEventListener('dragover',ev=>ev.preventDefault());el.addEventListener('drop',ev=>{ev.preventDefault();dropOn(el);});});}
function quickPlay(index){const c=battle.player.hand[index];if(!c||c.cost>battle.player.mana)return;if(['equipment','mount'].includes(c.type)&&battle.player.board.length){const r=playCard(battle,'player',index,{side:'player',index:0});message=r.ok?`${c.name} 사용`:r.error;}else if(c.type==='spell'&&/적 하나|피해/.test(c.text)&&battle.enemy.board.length){const r=playCard(battle,'player',index,{side:'enemy',index:0});message=r.ok?`${c.name} 사용`:r.error;}else{const r=playCard(battle,'player',index);message=r.ok?`${c.name} 사용`:r.error;}render();}
let selectedAttacker=null;function selectAttacker(i){selectedAttacker=i;message=`${battle.player.board[i]?.name||''} 공격 대상 선택`;render();document.querySelectorAll('[data-target-side="enemy"]').forEach(el=>el.classList.add('targetable'));document.querySelectorAll('[data-target-side="enemy"]').forEach(el=>el.onclick=()=>{const t={side:'enemy',type:el.dataset.targetType,index:el.dataset.targetIndex!==undefined?+el.dataset.targetIndex:undefined};performAttack(i,t);});}
function dropOn(el){if(!drag)return;if(drag.kind==='card'){const target=el.dataset.targetSide?{side:el.dataset.targetSide,type:el.dataset.targetType,index:el.dataset.targetIndex!==undefined?+el.dataset.targetIndex:undefined}:null;const card=battle.player.hand[drag.index];const r=playCard(battle,'player',drag.index,target);message=r.ok?`${card.name} 사용`:r.error;}else{const target={side:el.dataset.targetSide,type:el.dataset.targetType,index:el.dataset.targetIndex!==undefined?+el.dataset.targetIndex:undefined};performAttack(drag.index,target,false);}drag=null;render();}
function performAttack(i,target,rerender=true){const attacker=battle.player.board[i];const r=attack(battle,'player',i,target);message=r.ok?`${attacker?.name||'부대'} 공격!`:r.error;if(r.ok)impact(target);if(rerender)render();}
function impact(target){setTimeout(()=>{const sel=target.type==='fortress'?`.fortress.${target.side}`:`[data-unit-side="${target.side}"][data-unit-index="${target.index}"]`;const el=document.querySelector(sel);el?.animate([{transform:'translateX(0)'},{transform:'translateX(-10px)'},{transform:'translateX(10px)'},{transform:'translateX(0)'}],{duration:240});},20);}
function runAi(){if(!battle||battle.winner)return;aiTurn(battle);message='나의 턴';render();}
render();
